# Generated by Django 3.1.6 on 2021-02-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awayteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nameteam', models.CharField(max_length=190)),
                ('score', models.CharField(max_length=190)),
                ('pos', models.CharField(max_length=190)),
                ('red_card', models.CharField(max_length=190)),
                ('ya_card', models.CharField(max_length=190)),
            ],
        ),
        migrations.CreateModel(
            name='Hometeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nameteam', models.CharField(max_length=190)),
                ('score', models.CharField(max_length=190)),
                ('pos', models.CharField(max_length=190)),
                ('red_card', models.CharField(max_length=190)),
                ('ya_card', models.CharField(max_length=190)),
            ],
        ),
    ]
